Repository TeamDATEROAD/DATEROAD-AOS, pull requests merged in 2025-04, with the labels that each got.

#26 [feat] 시청형 광고 구현
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/teamdateroad/DateRoadApp.kt
  app/src/main/java/org/sopt/teamdateroad/data/dataremote/datasource/UserPointRemoteDataSource.kt
  app/src/main/java/org/sopt/teamdateroad/data/dataremote/datasourceimpl/UserPointRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/teamdateroad/data/dataremote/service/UserPointService.kt
  app/src/main/java/org/sopt/teamdateroad/data/repositoryimpl/UserPointRepositoryImpl.kt
  app/src/main/java/org/sopt/teamdateroad/domain/repository/UserPointRepository.kt
  app/src/main/java/org/sopt/teamdateroad/domain/usecase/PostAdsPointUseCase.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/type/OneButtonDialogWithDescriptionType.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/coursedetail/CourseDetailContract.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/pointhistory/PointHistoryContract.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/pointhistory/PointHistoryViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feat

#31 [feat] 포인트 로깅 추가
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/util/Constraints.kt
Labels: feat

#32 [fix] : 일정/코스 Date 범위 변경
  app/src/main/java/org/sopt/teamdateroad/presentation/util/Constraints.kt
Labels: fix

#34 [refactor] 장소 검색 LazyPaging 로직 개선
  app/src/main/java/org/sopt/teamdateroad/data/dataremote/datasourceimpl/PlaceSearchDataSourceImpl.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/component/PlaceSearchBottomSheet.kt
Labels: refactor

#36 fix: 장소 등록 키보드, 바텀시트 애니메이션 겹침 해결
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollScreen.kt
Labels: fix

#42 1차 QA 반영
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/component/card/DateRoadCourseCard.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/component/view/DateRoadEmptyView.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollContract.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollThirdScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/component/PlaceSearchBottomSheet.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/home/component/HomeTopBar.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/look/LookScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/mycourse/MyCourseScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/past/PastScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/pointhistory/PointHistoryScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/read/ReadScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/signin/SignInScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/timeline/TimelineScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/util/Constraints.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/util/view/NumberCommaTransformation.kt
  app/src/main/res/values/strings.xml
Labels: feat

#45 1차 QA 반영-2
  app/src/main/java/org/sopt/teamdateroad/presentation/type/DateChipGroupType.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/component/card/DateRoadPlaceCard.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/component/tag/DateRoadTextTag.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollFirstScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollSecondScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/component/PlaceSearchBottomSheet.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/navigator/component/MainNavHost.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/ui/timelinedetail/navigation/TimelineDetailNavigation.kt
  app/src/main/java/org/sopt/teamdateroad/presentation/util/Constraints.kt
  app/src/main/res/values/strings.xml
Labels: fix, feat
